application: gu-tuser-tracker
version: 3
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
- url: /tasks/.*
  login: admin
  script: tasks.app
- url: /.*
  script: app.app

libraries:
- name: jinja2
  version: latest

builtins:
- remote_api: on